#!/usr/bin/env python3
"""Regenerate the card tiers of the card-remover mod.

WHY this exists: the Card Remover prices a card by its tier -- normal, miniboss
or MVP -- and rAthena records no such thing on the card. The tier is a fact
about the monster that drops it, so it is DERIVED from the pinned mob_db and
item_db of each era, and this script is the record of how.

THE RULE, per card (an item with Type: Card that some monster drops):

  a monster with Modes: Mvp     -> MVP
  a monster with Class: Boss    -> miniboss
  any other monster             -> normal

  Only "base" monsters count. Event, instance and champion copies -- E_, MD_,
  EP<n>_MD_, NG_, MIN_, G_, C1_..C5_, *_I, *_V, and Class Event / Battlefield /
  Guardian -- drop the card of the monster they copy, and would otherwise
  promote or demote it: the event Eddga (E_EDDGA) drops Bigfoot Card, and the
  champion Galion (C5_GALION, no Boss class) drops Galion Card. When only copies
  drop a card, the copies decide. Among the monsters that count, the highest
  tier wins.

  A card no monster drops is not listed, and the mod treats it as normal.

WHAT IT WRITES: registry/mods/card-remover/npc/card_tiers.txt, an NPC script
that fills $@cardremover_mvp[] and $@cardremover_mini[] with item ids at
start-up, choosing the era's lists with checkre(0).

    python3 scripts/gen-card-tiers.py --rathena ../rathena
"""

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_REL = "registry/mods/card-remover/npc/card_tiers.txt"

_ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
_ap.add_argument("--rathena", default=os.environ.get("RATHENA_DIR", os.path.join(ROOT, "vendor", "rathena")),
                 help="pinned rAthena checkout holding db/{re,pre-re}/*.yml (default: vendor/rathena)")
_ap.add_argument("--check", action="store_true",
                 help="exit 1 if the committed file differs from what would be written")
ARGS = _ap.parse_args()

COPY = re.compile(r"^(E_|MD_|EP\d+_MD_|NG_|MIN_|G_|C\d_)|_(I|V)$")
COPY_CLASSES = {"Event", "Battlefield", "Guardian"}
NORMAL, MINI, MVP = 0, 1, 2


def entries(path):
    """The '  - Id:' blocks of a rAthena YAML database, as text."""
    text = open(path, encoding="utf-8", errors="replace").read()
    return re.split(r"\n  - Id: ", text)[1:]


def field(block, name):
    match = re.search(rf"^    {name}: *(.+?) *$", block, re.M)
    return match.group(1) if match else None


def cards(db):
    """AegisName -> item id of every card in the era's item_db."""
    out = {}
    for name in ("item_db_etc.yml", "item_db_equip.yml", "item_db_usable.yml"):
        for block in entries(f"{db}/{name}"):
            if field(block, "Type") == "Card":
                out[field(block, "AegisName")] = int(block.split("\n", 1)[0])
    return out


def tiers(db):
    known = cards(db)
    sources = {}  # card -> [(tier, is_copy)]
    for block in entries(f"{db}/mob_db.yml"):
        aegis = field(block, "AegisName")
        klass = field(block, "Class") or "Normal"
        mvp = re.search(r"^    Modes:\n(?:      .*\n)*?      Mvp: true", block, re.M) is not None
        tier = MVP if mvp else MINI if klass == "Boss" else NORMAL
        is_copy = bool(COPY.search(aegis)) or klass in COPY_CLASSES
        for item in re.findall(r"^      - Item: *(\S+)", block, re.M):
            if item in known:
                sources.setdefault(item, []).append((tier, is_copy))
    out = {}
    for card, found in sources.items():
        base = [tier for tier, is_copy in found if not is_copy]
        out[known[card]] = max(base or [tier for tier, _ in found])
    return out


def setarray(name, ids):
    lines = []
    for start in range(0, len(ids), 16):
        chunk = ", ".join(str(i) for i in ids[start:start + 16])
        lines.append(f"\t\tsetarray {name}[{start}], {chunk};")
    return "\n".join(lines)


def era(db):
    found = tiers(db)
    mvp = sorted(i for i, t in found.items() if t == MVP)
    mini = sorted(i for i, t in found.items() if t == MINI)
    return setarray("$@cardremover_mvp", mvp) + "\n" + setarray("$@cardremover_mini", mini), len(mvp), len(mini)


def main():
    for sub in ("re", "pre-re"):
        if not os.path.exists(f"{ARGS.rathena}/db/{sub}/mob_db.yml"):
            sys.exit(f"missing {ARGS.rathena}/db/{sub}/mob_db.yml - pass --rathena pointing at the pinned checkout")
    renewal, re_mvp, re_mini = era(f"{ARGS.rathena}/db/re")
    prere, pre_mvp, pre_mini = era(f"{ARGS.rathena}/db/pre-re")
    text = f"""//===== Ragnarok Offline mod: card-remover ===================
//= GENERATED by scripts/gen-card-tiers.py -- do not edit by hand.
//= Which cards are MVP and miniboss cards, by item id, for each era.
//= Every other card is a normal card. The script's docstring has the rule.
//=   renewal: {re_mvp} MVP, {re_mini} miniboss
//=   pre-renewal: {pre_mvp} MVP, {pre_mini} miniboss
//============================================================

-	script	card_tiers#cardremover	-1,{{
	end;

OnInit:
	deletearray $@cardremover_mvp;
	deletearray $@cardremover_mini;
	if (checkre(0)) {{
{renewal}
	}} else {{
{prere}
	}}
	end;
}}
"""
    out = os.path.join(ROOT, OUT_REL)
    if ARGS.check:
        current = open(out, encoding="utf-8").read() if os.path.exists(out) else ""
        if current != text:
            sys.exit(f"{OUT_REL} is out of date - run scripts/gen-card-tiers.py")
        return
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print(f"wrote {OUT_REL}: renewal {re_mvp} MVP / {re_mini} miniboss, pre-renewal {pre_mvp} / {pre_mini}")


main()
